### ISSUE TITLE
Installing gddragonbones in godot 3.2 stable

### ISSUE THREAD

**Issue by IlyshaNil** [Ranoller/gddragonbones#3]
Could you explain please, how to install gddragonbones in Godot v3.2.stable.official?
I tried this way https://docs.godotengine.org/ru/stable/tutorials/plugins/editor/installing_plugins.html , but it's not working (does not appear in the list of plugins). I'm just learning to work with godot...

**Comment by Ranoller** [comment]
It's not a plugin, is a module,you need to compile godot yourself, simply put gddragonbones folder inside modules folder and compile godot.

**Comment by IlyshaNil** [comment]
Thank you, I got it, but now there is an error with godot file:

C:\<path>\godot\modules\gddragonbones\src\GDDisplay.h(5): fatal error C1083: Не удается открыть файл включение: servers/visual_server.h: No such file or directory,

**Comment by Ranoller** [comment]
You are not compiling godot 3.2 stable, you are compiling godot 4.0 master branch. Visual server was renamed... this plugin compiles with godot 4.0 before reduz merge vulkan branch with godot 4.0, after that... well... to much changed. I will give a shoot to adapt to recent master, but not inmediatly, i'm in the middle of other works sorry...

**Comment by IlyshaNil** [comment]
Oh, exactly! I cloned the release 3.2 source code and compiled it successfully - everything works correctly now. It is a great tool, thanks a lot!)
